In [1]:
%pip install pandas openpyxl

Requirement already satisfied: pandas in C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.6)
Requirement already satisfied: openpyxl in C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: et-xmlfile in C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

df = pd.read_csv(r'C:\Users\gokul\OneDrive\Documents\Datasets\customer_shopping_behavior.csv')

df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
df.describe(include = 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [8]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [9]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [10]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [11]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [12]:
df.groupby('category').size()

category
Accessories    1240
Clothing       1737
Footwear        599
Outerwear       324
dtype: int64

In [13]:
df.groupby('category')['age'].mean()

category
Accessories    44.224194
Clothing       43.782959
Footwear       44.442404
Outerwear      44.311728
Name: age, dtype: float64

In [14]:
labels = ['young adult', 'adult', 'middle-aged', 'senior']

bins = [17, 25, 40, 60, 100]
df['group_age'] = pd.cut(df['age'],bins= bins, labels = labels)

In [15]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount_(usd)     0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
group_age                 0
dtype: int64

In [16]:
df[['age', 'group_age']].head(20)

    age    group_age
0    55  middle-aged
1    19  young adult
2    50  middle-aged
3    21  young adult
4    45  middle-aged
5    46  middle-aged
6    63       senior
7    27        adult
8    26        adult
9    57  middle-aged
10   53  middle-aged
11   30        adult
12   61       senior
13   65       senior
14   64       senior
15   64       senior
16   25  young adult
17   53  middle-aged
18   52  middle-aged
19   66       senior

In [17]:
df.groupby('frequency_of_purchases').size()

frequency_of_purchases
Annually          572
Bi-Weekly         547
Every 3 Months    584
Fortnightly       542
Monthly           553
Quarterly         563
Weekly            539
dtype: int64

In [18]:
frequency_mapping = {'Annually'  : 365,
'Bi-Weekly'    :  7,
'Fortnightly'  : 14,
'Monthly'      : 30,
'Quarterly'    : 90,
'Weekly'       :  7}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [19]:
df[['purchase_frequency_days', 'frequency_of_purchases']]

      purchase_frequency_days frequency_of_purchases
0                        14.0            Fortnightly
1                        14.0            Fortnightly
2                         7.0                 Weekly
3                         7.0                 Weekly
4                       365.0               Annually
...                       ...                    ...
3895                      7.0                 Weekly
3896                      7.0              Bi-Weekly
3897                     90.0              Quarterly
3898                      7.0                 Weekly
3899                     90.0              Quarterly

[3900 rows x 2 columns]

In [20]:
df

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,group_age,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,middle-aged,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,young adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,middle-aged,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,young adult,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,middle-aged,365.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly,adult,7.0
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly,middle-aged,7.0
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly,middle-aged,90.0
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly,middle-aged,7.0
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly,middle-aged,90.0

In [21]:
df[['discount_applied', 'promo_code_used']]

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [22]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [23]:
(df['discount_applied'] != df['promo_code_used']).sum()

np.int64(0)

In [24]:
df.loc[(df['promo_code_used'] == 'Yes') & (df['discount_applied'] == 'No'), 'discount_applied'] = 'Yes'

In [25]:
df[(df['promo_code_used'] == 'Yes') & (df['discount_applied'] == 'No')].shape

(0, 20)

In [26]:
df

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,group_age,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,middle-aged,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,young adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,middle-aged,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,young adult,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,middle-aged,365.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly,adult,7.0
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly,middle-aged,7.0
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly,middle-aged,90.0
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly,middle-aged,7.0
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly,middle-aged,90.0

In [27]:
df = df.drop('promo_code_used', axis = 1)

In [28]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'group_age', 'purchase_frequency_days'],
      dtype='str')

In [29]:
!pip install pandas sqlalchemy pyodbc

Requirement already satisfied: pandas in C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.6)
Requirement already satisfied: sqlalchemy in C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.1.4)
Requirement already satisfied: pyodbc in C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (5.3.0)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [30]:
import pyodbc

print(pyodbc.drivers())

['SQL Server', 'ODBC Driver 17 for SQL Server', 'ODBC Driver 18 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [31]:
%pip install --upgrade --force-reinstall sqlalchemy pyodbc pandas

Collecting sqlalchemy
  Using cached sqlalchemy-2.1.4-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Collecting pyodbc
  Using cached pyodbc-5.3.0-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Collecting pandas
  Using cached pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Using cached typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.5.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting python-dateutil>=2.8.2 (from pandas)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.5-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached sqlalchemy-2.1.4-cp314-cp314-win_amd64.whl (2.4 MB)
Using cached pyodbc-5.3.0-cp314-cp314-win_amd64.whl (72 kB)
Using cached pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
Using cached numpy-2.5.4-cp314-cp314-win_amd64.whl (12.7 MB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Using cached tzdata-2026.5-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, typing-extensions, six, pyodbc, numpy, sqlalchemy, python-dateutil, pandas

  Attempting uninstall: tzdata

    Found existing installation: tzdata 2026.5

   ---------------------------------------- 0/8 [tzdata]
    Uninstalling tzdata-2026.5:
   ---------------------------------------- 0/8 [tzdata]
   ---------------------------------------- 0/8 [tzdata]
      Successfully uninstalled tzdata-2026.5
   ---------------------------------------- 0/8 [tzdata]
   ---------------------------------------- 0/8 [tzdata]
   ---------------------------------------- 0/8 [tzdata]
   ---------------------------------------- 0/8 [tzdata]
   ---------------------------------------- 0/8 [tzdata]
   ---------------------------------------- 0/8 [tzdata]
   ---------------------------------------- 0/8 [tzdata]
   ---------------------------------------- 0/8 [tzdata]
   ---------------------------------------- 0/8 [tzdata]
  Attempting uninstall: typing-extensions
   ---------------------------------------- 0/8 [tzdata]
    Found existing installation: typing_extensions 4.16.0
   ---------------------------------------- 0/8 [tzdata]
    Uninstalling typing_extensions-4.16.0:
   ---------------------------------------- 0/8 [tzdata]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ----- ---------------------------------- 1/8 [typing-extensions]
      Successfully uninstalled typing_extensions-4.16.0
   ----- ---------------------------------- 1/8 [typing-extensions]
  Attempting uninstall: six
   ----- ---------------------------------- 1/8 [typing-extensions]
    Found existing installation: six 1.17.0
   ----- ---------------------------------- 1/8 [typing-extensions]
    Uninstalling six-1.17.0:
   ----- ---------------------------------- 1/8 [typing-extensions]
   ---------- ----------------------------- 2/8 [six]
   ---------- ----------------------------- 2/8 [six]
   ---------- ----------------------------- 2/8 [six]
   ---------- ----------------------------- 2/8 [six]
      Successfully uninstalled six-1.17.0
   ---------- ----------------------------- 2/8 [six]
  Attempting uninstall: pyodbc
   ---------- ----------------------------- 2/8 [six]
    Found existing installation: pyodbc 5.3.0
   ---------- ----------------------------- 2/8 [six]
   --------------- ------------------------ 3/8 [pyodbc]
    Uninstalling pyodbc-5.3.0:
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
      Successfully uninstalled pyodbc-5.3.0
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
   --------------- ------------------------ 3/8 [pyodbc]
  Attempting uninstall: numpy
   --------------- ------------------------ 3/8 [pyodbc]
    Found existing installation: numpy 2.5.4
   --------------- ------------------------ 3/8 [pyodbc]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
    Uninstalling numpy-2.5.4:
   -------------------- ------------------- 4/8 [numpy]
      Successfully uninstalled numpy-2.5.4
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
   -------------------- ------------------- 4/8 [numpy]
  Attempting uninstall: sqlalchemy
   -------------------- ------------------- 4/8 [numpy]
    Found existing installation: SQLAlchemy 2.1.4
   -------------------- ------------------- 4/8 [numpy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
    Uninstalling SQLAlchemy-2.1.4:
   ------------------------- -------------- 5/8 [sqlalchemy]
      Successfully uninstalled SQLAlchemy-2.1.4
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [sqlalchemy]
  Attempting uninstall: python-dateutil
   ------------------------- -------------- 5/8 [sqlalchemy]
    Found existing installation: python-dateutil 2.9.0.post0
   ------------------------- -------------- 5/8 [sqlalchemy]
   ------------------------------ --------- 6/8 [python-dateutil]
    Uninstalling python-dateutil-2.9.0.post0:
   ------------------------------ --------- 6/8 [python-dateutil]
      Successfully uninstalled python-dateutil-2.9.0.post0
   ------------------------------ --------- 6/8 [python-dateutil]
   ------------------------------ --------- 6/8 [python-dateutil]
  Attempting uninstall: pandas
   ------------------------------ --------- 6/8 [python-dateutil]
    Found existing installation: pandas 3.0.6
   ------------------------------ --------- 6/8 [python-dateutil]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
    Uninstalling pandas-3.0.6:
   ----------------------------------- ---- 7/8 [pandas]
      Successfully uninstalled pandas-3.0.6
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ---------------------------------------- 8/8 [pandas]

Successfully installed numpy-2.5.4 pandas-3.0.6 pyodbc-5.3.0 python-dateutil-2.9.0.post0 six-1.17.0 sqlalchemy-2.1.4 typing-extensions-4.16.0 tzdata-2026.5
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\gokul\AppData\Local\Temp\pip-uninstall-t1_sk5r7'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\~~mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\~~mpy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\gokul\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\~-ndas'.
  You can safely remove it manually.

In [32]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus


# ============================================
# SQL SERVER DETAILS
# ============================================

server = r"localhost\SQLEXPRESS"
database = "CustomerDB"
driver = "ODBC Driver 18 for SQL Server"


# ============================================
# CONNECTION
# ============================================

connection_string = (
    f"DRIVER={{{driver}}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
    f"TrustServerCertificate=yes;"
)


engine = create_engine(
    "mssql+pyodbc:///?odbc_connect="
    + quote_plus(connection_string)
)


# ============================================
# TEST CONNECTION
# ============================================

with engine.connect():
    print("SQL Server connection successful!")

SQL Server connection successful!

In [33]:
table_name = "customer_shopping_behavior"

df.to_sql(
    name=table_name,
    con=engine,
    if_exists="replace",
    index=False
)

print("Data uploaded successfully!")

Data uploaded successfully!